app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_main:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: /

nelmio_api_doc_index:
    path: /api/doc
    defaults: { _controller: NelmioApiDocBundle:ApiDoc:index }
    methods: [ 'GET' ]